"""0003_callback_inbox_outbox

Revision ID: 0df9f359346b
Revises: 73918cca1507
Create Date: 2026-06-11 19:02:01.753432

callback_inbox: 三元组 (tenant_id, source, request_id) 幂等唯一约束。
callback_outbox: dispatcher 扫表路径，status 加索引。
两表 updated_at 在 MySQL 补 ON UPDATE CURRENT_TIMESTAMP（dialect guard，对称 downgrade）。
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0df9f359346b"
down_revision: Union[str, Sequence[str], None] = "73918cca1507"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_ON_UPDATE_TABLES = ("callback_inbox", "callback_outbox")

# MySQL 专属：ON UPDATE CURRENT_TIMESTAMP —— SQLite 无此语法，用 dialect guard 隔离
# MODIFY COLUMN 重申列类型为 MySQL 必需（ALTER 须完整指定）；
# 新库无数据无锁风险，存量库执行需评估表锁（规范 14：高峰期禁止 DDL）。
_MYSQL_UPGRADE_TMPL = (
    "ALTER TABLE {table} MODIFY updated_at DATETIME NOT NULL"
    " DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"
)
_MYSQL_DOWNGRADE_TMPL = (
    "ALTER TABLE {table} MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "callback_inbox",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "source", "request_id", name="uq_inbox_tenant_src_req"),
    )
    op.create_index(
        op.f("ix_callback_inbox_tenant_id"), "callback_inbox", ["tenant_id"], unique=False
    )
    op.create_table(
        "callback_outbox",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("target", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_callback_outbox_status"), "callback_outbox", ["status"], unique=False)
    op.create_index(
        op.f("ix_callback_outbox_tenant_id"), "callback_outbox", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###

    # MySQL 专属：两张新表 updated_at 补 ON UPDATE CURRENT_TIMESTAMP
    if op.get_bind().dialect.name == "mysql":  # pragma: no cover
        for table in _ON_UPDATE_TABLES:
            op.execute(_MYSQL_UPGRADE_TMPL.format(table=table))


def downgrade() -> None:
    """Downgrade schema."""
    # MySQL 专属：还原 updated_at（去掉 ON UPDATE）
    if op.get_bind().dialect.name == "mysql":  # pragma: no cover
        for table in reversed(_ON_UPDATE_TABLES):
            op.execute(_MYSQL_DOWNGRADE_TMPL.format(table=table))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_callback_outbox_tenant_id"), table_name="callback_outbox")
    op.drop_index(op.f("ix_callback_outbox_status"), table_name="callback_outbox")
    op.drop_table("callback_outbox")
    op.drop_index(op.f("ix_callback_inbox_tenant_id"), table_name="callback_inbox")
    op.drop_table("callback_inbox")
    # ### end Alembic commands ###
