"""0002_idempotency_status_idx

Revision ID: 73918cca1507
Revises: f78c3a297e5c
Create Date: 2026-06-11 18:42:55.231937

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "73918cca1507"
down_revision: Union[str, Sequence[str], None] = "f78c3a297e5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_ON_UPDATE_TABLES = ("bank_txn_order", "bank_txn_leg", "idempotency_record")

# MySQL 专属：ON UPDATE CURRENT_TIMESTAMP —— SQLite 无此语法，用 dialect guard 隔离
_MYSQL_UPGRADE_TMPL = (
    "ALTER TABLE {table} MODIFY updated_at DATETIME NOT NULL"
    " DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"
)
_MYSQL_DOWNGRADE_TMPL = (
    "ALTER TABLE {table} MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idempotency_record",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("business_scope", sa.String(length=48), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("method", sa.String(length=8), nullable=False),
        sa.Column("path", sa.String(length=128), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("first_response", sa.JSON(), nullable=True),
        sa.Column("final_effect_id", sa.String(length=64), nullable=True),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "business_scope", "idempotency_key", name="uq_idem_triple"
        ),
    )
    op.create_index(
        op.f("ix_idempotency_record_tenant_id"),
        "idempotency_record",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(op.f("ix_bank_txn_order_status"), "bank_txn_order", ["status"], unique=False)
    # ### end Alembic commands ###

    # MySQL 专属：三张表 updated_at 补 ON UPDATE CURRENT_TIMESTAMP
    if op.get_bind().dialect.name == "mysql":  # pragma: no cover
        for table in _ON_UPDATE_TABLES:
            op.execute(_MYSQL_UPGRADE_TMPL.format(table=table))


def downgrade() -> None:
    """Downgrade schema."""
    # MySQL 专属：还原 updated_at（去掉 ON UPDATE）
    if op.get_bind().dialect.name == "mysql":  # pragma: no cover
        for table in reversed(_ON_UPDATE_TABLES):
            op.execute(_MYSQL_DOWNGRADE_TMPL.format(table=table))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bank_txn_order_status"), table_name="bank_txn_order")
    op.drop_index(op.f("ix_idempotency_record_tenant_id"), table_name="idempotency_record")
    op.drop_table("idempotency_record")
    # ### end Alembic commands ###
